In [1]:
print("hello")

hello

In [15]:
import numpy as np
l1=[2,3,4,5,6]
a=np.array(l1)
a.shape

s1=np.array([[1,2],[1]])
s1.shape

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [16]:
m=np.array([1,[],[0,9],4])
m

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [ ]:
data=np.array([[1,96,6,6],[2,97,6,7],[3,98,5,6],[4,99,5,7],[5,99,7,8]])
data[:,1]

In [42]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "marks":[80,90,np.nan,70]
})

df.isnull()

   marks
0  False
1  False
2   True
3  False

In [32]:
import pandas as pd


data = {
    "Name":["Dhruv","Raj","Aman"],
    "Age":[20,21,22],
    "Marks":[85,90,95]
}

df = pd.DataFrame(data)
df

    Name  Age  Marks
0  Dhruv   20     85
1    Raj   21     90
2   Aman   22     95

In [43]:
import os


with open("student.txt", "w") as file:
    file.write("Dhruv\n")
    file.write("Marks: 90\n")
    file.write("Course: Python")

print("Data written successfully")



with open("student.txt", "r") as file:
    content = file.read()
    print("\nComplete File Content:")
    print(content)



with open("student.txt", "r") as file:
    print("\nReading line by line:")
    
    for line in file:
        print(line.strip())



with open("student.txt", "r") as file:
    print("\nFirst Line:")
    print(file.readline())



with open("student.txt", "a") as file:
    file.write("\nGrade: A")

print("\nNew data appended")


# READ AFTER APPEND
with open("student.txt", "r") as file:
    print("\nUpdated File:")
    print(file.read())


# CHECK FILE EXISTS
if os.path.exists("student.txt"):
    print("\nFile exists")


# FILE POINTER POSITION
with open("student.txt", "r") as file:
    
    print("\nCursor Position:")
    print(file.tell())

    file.read(5)

    print("\nCursor Position After Reading 5 Characters:")
    print(file.tell())

    file.seek(0)

    print("\nCursor Reset:")
    print(file.tell())


# CREATE NEW FILE
try:
    with open("newfile.txt", "x") as file:
        print("\nNew file created")

except FileExistsError:
    print("\nFile already exists")


# DELETE FILE
choice = input("\nDo you want to delete newfile.txt? (yes/no): ")

if choice == "yes":
    
    if os.path.exists("newfile.txt"):
        os.remove("newfile.txt")
        print("File deleted")

    else:
        print("File not found")

Data written successfully

Complete File Content:
Dhruv
Marks: 90
Course: Python

Reading line by line:
Dhruv
Marks: 90
Course: Python

First Line:
Dhruv


New data appended

Updated File:
Dhruv
Marks: 90
Course: Python
Grade: A

File exists

Cursor Position:
0

Cursor Position After Reading 5 Characters:
5

Cursor Reset:
0

New file created

In [ ]:
import pandas as pd
from openpyxl import load_workbook


df = pd.DataFrame({
    "Name": ["Dhruv"]
  
})


df.to_excel("students.xlsx", index=False)

print("Excel file created")



data = pd.read_excel("students.xlsx")

print(data)



wb = load_workbook("students.xlsx")

sheet = wb.active


sheet["B2"] = "Hello, World"


wb.save("students.xlsx")

print("Hello World written at b2")

Excel file created
    Name
0  Dhruv
Hello World written at b2

In [ ]:
import requests


API_KEY = "229bb6342139de7200c4592ed204b1d8"       
CITY    = "London"                  
UNITS   = "metric"                  
BASE_URL = "https://api.openweathermap.org/data/2.5/weather"


params = {
    "q":     CITY,
    "appid": API_KEY,
    "units": UNITS
}



response = requests.get(BASE_URL, params=params)

# Check if request was successful
if response.status_code != 200:
    print(f"❌ Error {response.status_code}: {response.json().get('message')}")
    exit() # Exit the script if the API call fails

data = response.json()   # Convert JSON response → Python dict

\
rows = [
    ("City",             data["name"]),
    ("Country",          data["sys"]["country"]),
    ("Weather",          data["weather"][0]["description"].title()),
    ("Temperature (°C)", f"{data['main']['temp']} °C"),
    ("Feels Like",       f"{data['main']['feels_like']} °C"),
    ("Min Temp",         f"{data['main']['temp_min']} °C"),
    ("Max Temp",         f"{data['main']['temp_max']} °C"),
    ("Humidity",         f"{data['main']['humidity']} %"),
    ("Pressure",         f"{data['main']['pressure']} hPa"),
    ("Wind Speed",       f"{data['wind']['speed']} m/s"),
    ("Visibility",       f"{data.get('visibility', 'N/A')} m"),
    ("Cloudiness",       f"{data['clouds']['all']} %"),
]

# ─────────────────────────────────────────
# STEP 4 — DISPLAY IN ROWS & COLUMNS
# ─────────────────────────────────────────
print("\n" + "=" * 40)
print(f"  🌤  WEATHER REPORT — {CITY.upper()}")
print("=" * 40)
print(f"{'FIELD':<20} {'VALUE':<20}")
print("-" * 40)

for field, value in rows:
    print(f"{field:<20} {value:<20}")

print("=" * 40)

❌ Error 401: Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.

KeyError: 'name'

: